### ISSUE TITLE
Message from a supporter.

### ISSUE THREAD

**Issue by gndl** [savonet/ocaml-lilv#1]
I'm delighted to see this new project, I started the same project recently. The version with ctypes is in the [ctype_ffi](https://framagit.org/gndl/ocaml-lilv/tree/ctype_ffi) branch (if it can be of any use to you).
PS: sorry to use the issue tracker for this message, I do not know in which email list to post.

**Comment by smimram** [comment]
Thanks for your message! :)

I did not know about your binding, looks like it's much more complete and advanced. In particular, you use the stub generation, which seems to be the way to go. And two bindings for lilv look like a really useless duplication of efforts.

The only things I am not entirely fond of in your approach is the use of monadic style for errors instead of exceptions (but that's quite minor).

How shall we proceed? Do you want to release your binding on opam so that I can adapt the code on the Liquidsoap side? Do you want some help on some points?

**Comment by gndl** [comment]
I think it would be better for the project to be carried out by the Savonet team for efficiency and durability reasons. If you agree, I am ready to cancel my project and I would be happy to contribute to yours. In this case, you have the power to decide on design choices such as how to handle errors.
That said, if you really prefer to leave this work to others, I can continue the project.

**Comment by smimram** [comment]
Great, let's say that this repository is the main one then. I'd be more than happy to incorporate pull requests from you and give you access to the repo if you need!

BTW, I'm being curious now: why did you need this for? :)

**Comment by gndl** [comment]
> BTW, I'm being curious now: why did you need this for? :)

To use Lv2 plugins in [Graffophone](https://github.com/gndl/graffophone).

**Comment by smimram** [comment]
I did not know about it, sounds great!
